remote_theme: pmarsceill/just-the-docs

# Auxiliary links for the upper right hand corner
aux_links:
  "LinkedIn Link":
  - "http://www.linkedin.com/in/byeongjae-ben-chun-745b551b"
  "Contact Ben":
  - "mailto:bending456@gmail.com"

title: "Byeong Jae (Ben) Chun's Portfolio"
theme: jekyll-theme-cayman