title: "Ben Chun Portfolio"
description: "Chemical Engineer | Computational Biologist | AI Enthusiast"
baseurl: ""
url: "https://ben-chun.github.io"

theme: minimal-mistakes-jekyll

author:
  name: "Byeongjae (Ben) Chun"
  avatar: "/assets/images/profile.jpg"  # Optional
  bio: "Technical Lead | Chemical Engineering | Molecular Simulation"

plugins:
  - jekyll-include-cache

# Sidebar nav setup
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "main"

markdown: kramdown